[package]
name = "firmware-core"
version = "0.1.0"
edition = "2021"
description = "Platform-indipendent code for the 3D printer's firmware"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
embedded-hal = { version = "0.2.7", features = ["unproven"] }

enumset = "1.1.2"

pid_control = "0.7.2"