name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  
  PRINTER_PASSWORD: ${{ secrets.PRINTER_PASSWORD }}
  PRINTER_PASSWORD_PEPPERS: ${{ secrets.PRINTER_PASSWORD_PEPPERS }}
  WIFI_PASSWORD: ${{ secrets.WIFI_PASSWORD }}
  WIFI_SSID: ${{ secrets.WIFI_SSID }}

jobs:
  build:
    defaults:
      run:
        working-directory: firmware

    strategy:
      matrix:
        profile: [dev, release]
        toolchain: [nightly]
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v3
    - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
    - name: Build
      run: cargo build --verbose --package firmware-core --profile ${{ matrix.profile }}
    - name: Run tests
      run: cargo test --verbose --package firmware-core --profile ${{ matrix.profile }}
